Repository CMU-313/nodebb-f24-the-turtles, pull requests merged in 2024-10, with the labels that each got.

#48 US-34 Add backend functionality for marking topic as public/private and their associated unit tests
  .mocharc.yml
  node_modules/nodebb-plugin-composer-default/static/lib/composer.js
  node_modules/nodebb-plugin-composer-default/static/templates/partials/composer-formatting.tpl
  node_modules/nodebb-plugin-composer-default/static/templates/partials/composer-title-container.tpl
  public/language/en-GB/modules.json
  public/openapi/components/schemas/TopicObject.yaml
  public/openapi/read/topic/topic_id.yaml
  public/openapi/read/unread.yaml
  src/api/categories.js
  src/categories/topics.js
  src/controllers/category.js
  src/privileges/topics.js
  src/topics/create.js
  src/topics/index.js
  test/topics.js
Labels: enhancement

#52 Added more thorough test for Private topic permissions and fixed lint
  src/categories/topics.js
  src/topics/create.js
  test/topics.js
Labels: enhancement

#54 US9 - Fix lint error
  dump.rdb
  install/package.json
Labels: enhancement

#57 Edit Test Cases
  package-lock.json
  package.json
  test/api.js
  test/categories.js
  test/controllers.js
  test/posts.js
  test/topics.js
  test/user.js
Labels: testing

#60 Integrate JSHint into Codebase Workflow for Automated Linting
  .jshintrc
  package.json
  src/api/users.js
  src/categories/watch.js
  src/controllers/accounts/chats.js
  src/controllers/errors.js
  src/controllers/helpers.js
  src/database/mongo/sorted/intersect.js
  src/database/redis/connection.js
  src/flags.js
  src/groups/ownership.js
  src/messaging/rooms.js
  src/messaging/unread.js
  src/meta/configs.js
  src/notifications.js
  src/privileges/helpers.js
  src/routes/write/users.js
  src/socket.io/categories.js
  src/socket.io/modules.js
  src/topics/follow.js
  src/topics/tags.js
  src/topics/unread.js
  src/user/admin.js
  src/user/auth.js
  src/user/categories.js
  src/user/email.js
  src/user/index.js
  src/user/online.js
  src/user/posts.js
Labels: workflow
